apiVersion: v1
kind: Pod
metadata:
  name: ciscose-nginx-demo
  namespace: ciscose
  labels:
    app: ciscose-demo-app
    org: ciscose
    env: dcloud
spec:
  containers:
    - name: web-server
      image: nginx:latest
