apiVersion: v1
kind: Pod
metadata:
  name: lab1-express-pod
  labels:
    app: lab1-express
spec:
  containers:
    - name: express
      image: lab1-express:1.0
      imagePullPolicy: Never
      ports:
        - containerPort: 3000
